"""Generate the small local UI glyph set from a user-supplied font (Pillow)."""
import sys
from pathlib import Path
import PIL

# Pillow 9.x is not compatible with Python 3.12. Fail before calling native
# font rendering code rather than letting an unsupported binary crash.
if sys.version_info >= (3, 12) and tuple(map(int, PIL.__version__.split('.')[:2])) < (10, 1):
    raise SystemExit(
        'Unsupported Python/Pillow combination. Run with '
        'build/font-tools/Scripts/python.exe (see tools/README.md).')

from PIL import Image, ImageDraw, ImageFont
chars = sorted(set("数控电源演示电压电流设定限流温度输出关闭刷新率运行"))
font = ImageFont.truetype(sys.argv[1], 16, layout_engine=ImageFont.Layout.BASIC)
bitmap=[]; desc=['{0}']
for c in chars:
    im=Image.new('L',(16,18)); ImageDraw.Draw(im).text((0,0),c,font=font,fill=255,anchor='lt')
    vals=[v//17 for v in im.tobytes()]
    desc.append('{.bitmap_index=%d,.adv_w=256,.box_w=16,.box_h=18,.ofs_x=0,.ofs_y=-3}'%len(bitmap))
    bitmap.extend((vals[i]<<4)|vals[i+1] for i in range(0,len(vals),2))
start=ord(chars[0]); offsets=','.join(str(ord(c)-start) for c in chars)
out='/* Generated by tools/generate_ui_font.py; local font subset, 16px / 4bpp. */\n#include "lvgl.h"\n'
out+='static const uint8_t bitmap[]={'+','.join(map(str,bitmap))+'};\n'
out+='static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={'+','.join(desc)+'};\n'
out+='static const uint16_t unicodes[]={'+offsets+'};\n'
out+='static const lv_font_fmt_txt_cmap_t cmap[]={ {.range_start=%d,.range_length=%d,.glyph_id_start=1,.unicode_list=unicodes,.list_length=%d,.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY} };\n'%(start,ord(chars[-1])-start+1,len(chars))
out+='static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmap,.cmap_num=1,.bpp=4};\n'
out+='const lv_font_t ui_font_zh_16={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=18,.base_line=3,.dsc=&dsc,.fallback=&lv_font_montserrat_14};\n'
Path('Core/Src/ui_font_zh_16.c').write_text(out,encoding='utf-8')
